coverage:
  precision: 2
  range:
    - 50.0
    - 75.0
  round: down
  status:
    patch:
      default:
        target: 50.0
    project:
      default:
        target: auto
        threshold: 1%
ignore:
  - "**/*_test.go"
  - "**/*_mock.go"
  - "**/pgdb.go"
